fail_fast: false
default_language_version:
  python: python3
default_stages:
  - push
minimum_pre_commit_version: 2.16.0
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml