language: python
python:
- '3.7'
script: true
deploy:
  provider: pypi
  username: __token__
  on:
    tags: true
  password:
    secure: AHOmeMxJligs8mMZ2+mDcl5ii3twXyRC5+JoUZIKLdglbrvPoJypioebQBWDBC18oTO5AeGe38H49OxoWHailBAEff3HacJYc+v1/4h25TyxWeHz4l1GJuDnfrzVXky+Jgnsqmw6IBODvKCTDj55CajU/p5bLIksAOIjs3k6fIU/yhnd/1mStqBcHySPiWfyRlWgMvJGREayu7Che2glgHo5mts6yAXdBc4JWz/HXEm4gs5SdkKyrAS8fOFEqWMdcnD5s1blNzf0MNX1SIgQUIf3/ty/j0m1UIlqwhm66nR/AlMlqgqS9vPRK6E/N6PxsuI3O3LGu4xmDJJDpRAhhoxhmrz3n0WfNZl5oMADq+TR3e/3/tGxuPySTPXqlF0efp7kQsK/pZudZolrOK5QOU07quyGPGcmX7W/mY2urdkzoAFhlpdeDDlzY39qJNKSc9WuxfTQGtaHN5B3ANViedm29nU4geMOVZvLmWsTADltczxGltXPe4kIEXmIf20Z2vz0MwxrbPJcSa9UEr8k9ppEjoraG8cTEF0y/+4NDU82+SNPVmX/YBx+8Z2qbUKg4zSnEosC9uJidzPNe61VxwM9786pcHtMcyhh295pw9k6V3l0SaLLtQoaX65Oyu+UVklNWmKSg2tCOsJth6H9fUWZneIXvRWpwkY/2JEDlzo=
