language: python
python:
- '3.7'
script: true
deploy:
  provider: pypi
  username: __token__
  on:
    tags: true
  password:
    secure: DpyNKaz/bDDJdctNZf/wOmmlPArlxj16ZFN5WIkvXw2rrwvIGL7oxBiEuTG82Rhw2MN1JUsN++urYa0BSK+S/eFWGLNglmeyfva2HE8FmSmhWaG5JTCE0/j0wUN+4jasrSCEBnlWK2TwBRweTZDFkcBJ2RP56RkdSYQcfs398IhhBAbPgA/VgHoHCZM6VmhO+dPaErrIUAHEq/iTjA47UzEotEUtftiPrFH93vfFI0MITxSx4TnYORzvMEO4JFyLbVSTE7ojl2oA0TZxGKu7tTwNbgx3iff3XDiYB3PWeT7u/vQPh63sxGF3frDjSHd9jcd9LCY+XA7tagZ9UiZ+waCpNborvEpaa/6ZgHENYCtrPw6oijZR8kwYOfdHPoXPYcd1b6kHnehYFibwnbMvWNMm/HMdCZAHQOG4y/2fZBwUQmJx3aWdrXiVlK6DDHzRVoj/HiNiGjwYIxN/S93znfuXMHoyONbr7I6tBaORqY6h78Ymsyjp4JXjbFvwGyx3eEZP9nElOpSg0nXaFkxRilpldZ7myc4CV2t8dRZmV816WYcqLGywJFCMwLfeqAyejXrwNUPXp/IVSIlzg1hSsULzpxSM4DfH/PBaLBHjJwz8gHaHQ8gMjWg0XP+tz1dKDCX/495xKNplE/PpPLY3DMLvCIwEyIcnnplxRXUyoX0=
