language: python
python:
- '3.7'
script: true
deploy:
  provider: pypi
  username: __token__
  on:
    tags: true
  password:
    secure: abBd4ilXWaG7hybumoRnnVFQUgz/4cE3IBxQy4M9Wvxma9qkJ7xYKZBFZ11qqiq66PpfZ6JMtvoy4/9HcqpEM/hsrL10yexN3BKdhvkT23Qs1WEJWFtw2ne/PAPWptaablMGp1VYKZZ7eV1jlevRGX2wDUt/pZOUOoa2BOtGbEm0b+mUp7MBa/+xJCyk2d/fLCwUSR4xEWERMncghvwpYrEQipEjW9SnnWNpsXD8OR1naPrC94MND9ZVfKDTwD4kOKxDN1yjFk7Xc5ZzbfjHMCf98p5BWBuaZ0rs82mh6tnUFaC9lbKOTrX8M+Lz8BnX3tDWnmeu/3If1IThEUr0+NQYhU+x8CTRK6AqEJSdI6ZHEBEnmiMDDMpAAmCr7i4YnBEo+cpO8qOIa9IP31B9epeBAp6apc4aHsrtt8/CgeH27nZ+2hHWfaxGedjNFVcZxcfPkCYyLSFUOZy3kifxVFdvOvor5+XgQwklHXsgWravSPFzjVAstiu0d6+JR0cu0DGVTI6YipVM3jQKRhxdLz/K/BbEF/GR6jkZYDMAr+KVOck2fWl3fVc8NSg10EzjoGrhU8f45LaNdaYpNtun8iSBq1rWkwFIb04zlcLJJsEjwznzh6GkU9kZPF39gCbIyIbECN/oL6mopDwp6HVtf99ZMqMVxHvCUZGA/HYuMRQ=
