"""
This file is modified from methylpy https://github.com/yupenghe/methylpy.

Author: Yupeng He

Notes added on 07/03/2022 - Difference between bismark and hisat-3n
Read mpileup doc first: http://www.htslib.org/doc/samtools-mpileup.html

For Bismark SE mapping:
Bismark converted the reads orientation based on their conversion type.
C to T conversion reads are always map to the forward strand, regardless of the R1 R2
G to A conversion reads are always map to the reverse strand, regardless of the R1 R2
Therefore, in the original bam-to-allc function, we simply consider the strandness in
the pileup format to distinguish which C needs to be counted.
There are two situations:
1. If the ref base is C, the read need to map to forward strand in order to be counted
[.ATCGN] corresponding to the forward strand
2. If the ref base is G, the read need to map to reverse strand in order to be counted
[,atcgn] corresponding to the reverse strand

For Hisat-3n PE or Biskarp PE mapping:
R1 R2 are mapped as their original orientation, therefore,
both the C to T and G to A conversion reads can have forward and reverse strand alignment.
We can not distinguish the conversion type by strand in input bam.
Here I add a check using the YZ tag of hisat-3n BAM file or XG tag of bismark BAM file.
If the YZ tag is "+" or XG tag is "CT", the read is C to T conversion, I change the flag to forward mapping (OT/OB, R2)
no matter R1 or R2 by read.is_forward = True
If the YZ tag is "-" or XG tag is "GA", the read is G to A conversion, I change the flag to reverse mapping (CTOT/CTOB, R1)
no matter R1 or R2 by read.is_forward = False
In this case, the read orientation is the same as bismark bam file, and the following base
count code no need to change.

"""
import os,sys
import collections
import logging
import pathlib
import shlex
import subprocess
from concurrent.futures import ProcessPoolExecutor, as_completed
import numpy as np
import pandas as pd
import pysam
import glob
import pickle
from ._doc import *
from ._open import open_allc, open_bam
from .utilities import genome_region_chunks

# logger
log = logging.getLogger(__name__)
log.addHandler(logging.NullHandler())


def _is_read_ct_conversion_hisat3n(read):
    return read.get_tag("YZ") == "+"


def _is_read_ct_conversion_bismark(read):
    return read.get_tag("XG") == "CT"

def determine_method(bam_path):
    fbam = pysam.AlignmentFile(bam_path, 'rb')
    read = fbam.__next__()
    fbam.close()
    if read.has_tag("YZ"):
        is_ct_func = _is_read_ct_conversion_hisat3n
    elif read.has_tag("XG"):
        is_ct_func = _is_read_ct_conversion_bismark
    else:
        raise ValueError(
            "The bam file reads has no conversion type tag "
            "(XG by bismark or YZ by hisat-3n). Please note that this function can "
            "only process bam files generated by bismark or hisat-3n."
        )
    return is_ct_func

def _convert_bam_strandness(in_bam_path, out_bam_path):
    is_ct_func = determine_method(in_bam_path)
    with pysam.AlignmentFile(in_bam_path) as in_bam, pysam.AlignmentFile(
        out_bam_path, header=in_bam.header, mode="wb"
    ) as out_bam:
        for read in in_bam:
            if is_ct_func(read):
                read.is_forward = True
                if read.is_paired:
                    read.mate_is_forward = True
            else:
                read.is_forward = False
                if read.is_paired:
                    read.mate_is_forward = False
            out_bam.write(read)
    return

def _read_faidx(faidx_path):
    """
    Read fadix of reference fasta file.

    samtools fadix ref.fa
    """
    return pd.read_csv(
        faidx_path,
        index_col=0,
        header=None,
        sep="\t",
        names=["NAME", "LENGTH", "OFFSET", "LINEBASES", "LINEWIDTH"],
    )


def _get_chromosome_sequence_upper(fasta_path, fai_df, query_chrom):
    """Read a whole chromosome sequence into memory."""
    chrom_pointer = fai_df.loc[query_chrom, "OFFSET"]
    tail = fai_df.loc[query_chrom, "LINEBASES"] - fai_df.loc[query_chrom, "LINEWIDTH"]
    seq = ""
    with open(fasta_path) as f:
        f.seek(chrom_pointer)
        for line in f:
            if line[0] == ">":
                break
            seq += line[:tail]  # trim \n
    return seq.upper()


def _get_bam_chrom_index(bam_path):
    result = subprocess.run(["samtools", "idxstats", bam_path], stdout=subprocess.PIPE, encoding="utf8").stdout

    chrom_set = set()
    for line in result.split("\n"):
        chrom = line.split("\t")[0]
        if chrom not in ["", "*"]:
            chrom_set.add(chrom)
    return pd.Index(chrom_set)

def calculate_mean_cov(
        gc_content,bam_file,min_mapq=10,min_base_quality=20,
        bin_size=500,num_bins=50, frac=0.2,it=3, delta=0.01):
    from statsmodels.nonparametric.smoothers_lowess import lowess
    import matplotlib.pylab as plt
    bam_file=os.path.expanduser(bam_file)
    bam_depth=f"{bam_file}.depth.txt"
    if not os.path.exists(bam_depth):
        cmd=f"samtools depth -q {min_base_quality} -Q {min_mapq} -J {bam_file} | awk '{{print($1\"-\"int(($2-1)/{bin_size})\"\\t\"$3)}}' | bedtools groupby -i stdin -g 1 -c 2 -o mean > {bam_depth}" # 1-based
        os.system(cmd)
    df_gc=pd.read_csv(os.path.expanduser(gc_content),sep='\t',
        header=None,usecols=[0,4],names=['ID','GC'])
    D=pd.read_csv(bam_depth,sep='\t',header=None,
                        names=['ID','mean_cov']).set_index('ID').mean_cov.to_dict() # 0-based
    df_gc['mean_cov']=df_gc.ID.map(D).fillna(0)

    global_avg_cov = df_gc['mean_cov'].mean() # 0.163
    df_gc['gc_bin'] = pd.cut(df_gc['GC'], bins=num_bins, labels=range(num_bins))
    bin_means = df_gc.groupby('gc_bin')['mean_cov'].mean().values
    gc_bins = np.linspace(0, 100, num_bins)
    
    # Model bias with LOWESS (using statsmodels), x is gc_bins, y is bin_means
    smoothed = lowess(bin_means, gc_bins, it=it, delta=delta, frac=frac, return_sorted=False) # return estimated y (mean coverage)
    # Plot the fit line
    fig, ax = plt.subplots(figsize=(5,3.5))
    ax.scatter(gc_bins, bin_means)
    ax.plot(gc_bins, smoothed, c="red",linewidth=2) # smoothed coverage
    ax.axhline(y=global_avg_cov, color='green', linestyle='--',zorder=-1)
    ax.set_xlabel("GC content (%)",fontsize=10)
    ax.set_ylabel("Smoothed average coverage",fontsize=10)
    plt.savefig(f"{bam_file}.smooth.pdf",dpi=300,bbox_inches='tight')
    correction_factors = global_avg_cov / smoothed  # Scale up low-coverage bins, gc_bins
    # df_gc=df_gc.loc[df_gc.mean_cov > global_avg_cov]
    D={i: factor for i,factor in enumerate(correction_factors)}
    df_gc['correction_factor']=df_gc.gc_bin.map(D)
    df_gc=df_gc.loc[df_gc.correction_factor.between(0,1)]
    factors=df_gc.set_index('ID').correction_factor.to_dict()
    f=open(f"{bam_file}.correction_factor.pkl",'wb')
    pickle.dump(factors,f,True)
    f.close()

def _bam_to_allc_worker(
    bam_path,reference_fasta,fai_df,output_path,
    region=None,num_upstr_bases=0,num_downstr_bases=2,
    buffer_line_number=100000,min_mapq=0,min_base_quality=1,
    compress_level=5,tabix=True,save_count_df=False,use_chroms=None,
):
    """None parallel bam_to_allc worker function, call by bam_to_allc."""
    # mpileup
    region_bed_path = None
    if region is None:
        # if use_chroms is given, restrict mpileup to those chromosomes via a BED
        # file (-l). Otherwise mpileup piles up the whole BAM, including decoy/alt
        # contigs whose pathological high-coverage sites can hang the parser.
        region_arg = ""
        if use_chroms is not None:
            target_chroms = [c for c in fai_df.index if c in use_chroms]
            region_bed_path = f"{output_path}.mpileup_regions.bed"
            with open(region_bed_path, "w") as bed_f:
                for chrom in target_chroms:
                    bed_f.write(f"{chrom}\t0\t{int(fai_df.loc[chrom, 'LENGTH'])}\n")
            region_arg = f"-l {region_bed_path} "
        mpileup_cmd = (
            f"samtools mpileup -Q {min_base_quality} "
            f"-q {min_mapq} -B {region_arg}-f {reference_fasta} {bam_path}"
        )
        pipes = subprocess.Popen(
            shlex.split(mpileup_cmd),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            universal_newlines=True,
            encoding="latin-1",
        )
    else:
        bam_handle = open_bam(
            bam_path,
            region=region,
            mode="r",
            include_header=True,
            samtools_parms_str=None,
        )
        mpileup_cmd = f"samtools mpileup -Q {min_base_quality} " f"-q {min_mapq} -B -f {reference_fasta} -"
        pipes = subprocess.Popen(
            shlex.split(mpileup_cmd),
            stdin=bam_handle.file,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            universal_newlines=True,
            encoding="latin-1",
        )

    result_handle = pipes.stdout

    output_file_handler = open_allc(output_path, mode="w", compresslevel=compress_level)

    # initialize variables
    complement = {"A": "T", "T": "A", "C": "G", "G": "C", "N": "N"}
    mc_sites = {"C", "G"}
    context_len = num_upstr_bases + 1 + num_downstr_bases
    cur_chrom = ""
    line_counts = 0
    total_line = 0
    out = ""
    seq = None  # whole cur_chrom seq
    # chr_out_pos_list = []
    # cur_out_pos = 0
    cov_dict = collections.defaultdict(int)  # context: cov_total
    mc_dict = collections.defaultdict(int)  # context: mc_total

    # process mpileup result
    for line in result_handle:
        fields = line.split("\t")
        # only consider chromosomes in the chroms whitelist
        if use_chroms is not None and fields[0] not in use_chroms:
            continue
        total_line += 1
        fields[2] = fields[2].upper()
        pos = int(fields[1]) - 1
        # if chrom changed, read whole chrom seq from fasta
        if fields[0] != cur_chrom:
            cur_chrom = fields[0]
            # chr_out_pos_list.append((cur_chrom, str(cur_out_pos)))
            # get seq for cur_chrom
            seq = _get_chromosome_sequence_upper(reference_fasta, fai_df, cur_chrom)

        if fields[2] not in mc_sites:
            continue

        # deal with indels
        read_bases = fields[4]
        incons_basecalls = read_bases.count("+") + read_bases.count("-")
        if incons_basecalls > 0:
            read_bases_no_indel = ""
            index = 0
            prev_index = 0
            while index < len(read_bases):
                if read_bases[index] == "+" or read_bases[index] == "-":
                    # get insert size
                    indel_size = ""
                    ind = index + 1
                    while True:
                        try:
                            int(read_bases[ind])
                            indel_size += read_bases[ind]
                            ind += 1
                        except Exception:
                            break
                    try:
                        # sometimes +/- does not follow by a number and
                        # it should be ignored
                        indel_size = int(indel_size)
                    except Exception:
                        index += 1
                        continue
                    read_bases_no_indel += read_bases[prev_index:index]
                    index = ind + indel_size
                    prev_index = index
                else:
                    index += 1
            read_bases_no_indel += read_bases[prev_index:index]
            fields[4] = read_bases_no_indel

        # count converted and unconverted bases
        if fields[2] == "C":
            # mpileup pos is 1-based, turn into 0 based
            try:
                context = seq[(pos - num_upstr_bases) : (pos + num_downstr_bases + 1)]
            except Exception:  # complete context is not available, skip
                continue
            unconverted_c = fields[4].count(".")
            converted_c = fields[4].count("T")
            cov = unconverted_c + converted_c
            if cov > 0 and len(context) == context_len:
                line_counts += 1
                data = (
                    "\t".join(
                        [
                            cur_chrom,
                            str(pos + 1),
                            "+",
                            context,
                            str(unconverted_c),
                            str(cov),
                            "1",
                        ]
                    )
                    + "\n"
                )
                cov_dict[context] += cov
                mc_dict[context] += unconverted_c
                out += data
                # cur_out_pos += len(data)

        elif fields[2] == "G":
            try:
                context = "".join(
                    [
                        complement[base]
                        for base in reversed(seq[(pos - num_downstr_bases) : (pos + num_upstr_bases + 1)])
                    ]
                )
            except Exception:  # complete context is not available, skip
                continue
            unconverted_c = fields[4].count(",")
            converted_c = fields[4].count("a")
            cov = unconverted_c + converted_c
            if cov > 0 and len(context) == context_len:
                line_counts += 1
                data = (
                    "\t".join(
                        [
                            cur_chrom,
                            str(pos + 1),  # ALLC pos is 1-based
                            "-",
                            context,
                            str(unconverted_c),
                            str(cov),
                            "1",
                        ]
                    )
                    + "\n"
                )
                cov_dict[context] += cov
                mc_dict[context] += unconverted_c
                out += data
                # cur_out_pos += len(data)

        if line_counts > buffer_line_number:
            output_file_handler.write(out)
            line_counts = 0
            out = ""

    if line_counts > 0:
        output_file_handler.write(out)
    result_handle.close()
    output_file_handler.close()

    if region_bed_path is not None and os.path.exists(region_bed_path):
        os.remove(region_bed_path)

    if tabix:
        subprocess.run(shlex.split(f"tabix -b 2 -e 2 -s 1 {output_path}"), check=True)

    count_df = pd.DataFrame({"mc": mc_dict, "cov": cov_dict})
    count_df["mc_rate"] = count_df["mc"] / count_df["cov"]

    total_genome_length = fai_df["LENGTH"].sum()
    count_df["genome_cov"] = total_line / total_genome_length

    if save_count_df:
        count_df.to_csv(output_path + ".count.csv")
        return None
    else:
        return count_df


def _aggregate_count_df(count_dfs):
    total_df = pd.concat(count_dfs)
    total_df = total_df.groupby(total_df.index).sum()
    total_df["mc_rate"] = total_df["mc"] / total_df["cov"]
    total_df["mc"] = total_df["mc"].astype(int)
    total_df["cov"] = total_df["cov"].astype(int)
    return total_df


@doc_params(
    compress_level_doc=compress_level_doc,
    cpu_basic_doc=cpu_basic_doc,
    reference_fasta_doc=reference_fasta_doc,
    convert_bam_strandness_doc=convert_bam_strandness_doc,
)
def bam_to_allc(
    bam_path,
    reference_fasta,
    output_path=None,
    cpu=1,
    num_upstr_bases=0,
    num_downstr_bases=2,
    min_mapq=10,
    min_base_quality=20,
    compress_level=5,
    save_count_df=False,
    convert_bam_strandness=True,keep_temp=False,
    chroms=None,
):
    """\
    Generate 1 ALLC file from 1 position sorted BAM file via samtools mpileup.

    Parameters
    ----------
    bam_path
        Path to 1 position sorted BAM file
    reference_fasta
        {reference_fasta_doc}
    output_path
        Path to 1 output ALLC file
    cpu
        {cpu_basic_doc} DO NOT use cpu > 1 for single cell ALLC generation.
        Parallel on cell level is better for single cell project.
    num_upstr_bases
        Number of upstream base(s) of the C base to include in ALLC context column,
        usually use 0 for normal BS-seq, 1 for NOMe-seq.
    num_downstr_bases
        Number of downstream base(s) of the C base to include in ALLC context column,
        usually use 2 for both BS-seq and NOMe-seq.
    min_mapq
        Minimum MAPQ for a read being considered, samtools mpileup parameter, see samtools documentation.
    min_base_quality
        Minimum base quality for a base being considered, samtools mpileup parameter,
        see samtools documentation.
    compress_level
        {compress_level_doc}
    save_count_df
        If true, save an ALLC context count table next to ALLC file.
    convert_bam_strandness
        {convert_bam_strandness_doc}
    chroms
        Restrict processing to a whitelist of chromosomes. Accepts a list of
        names, a comma-separated string ('chr1,chr2'), or a path to a
        chromosome-size / .fai file (first column). If provided, only the
        listed chromosomes are processed; BAM contigs not listed (e.g. decoy
        contigs) are ignored. Consistent with ``cytozip.bam.bam_to_cz``'s
        ``chroms`` parameter.

    Returns
    -------
    count_df
        a pandas.DataFrame for overall mC and cov count separated by mC context.
    """
    buffer_line_number = 100000
    tabix = True

    # Check fasta index
    if not pathlib.Path(reference_fasta).exists():
        raise FileNotFoundError(f"Reference fasta not found at {reference_fasta}.")
    if not pathlib.Path(reference_fasta + ".fai").exists():
        raise FileNotFoundError("Reference fasta not indexed. Use samtools faidx to index it and run again.")
    fai_df = _read_faidx(pathlib.Path(reference_fasta + ".fai"))

    # optionally restrict to a whitelist of chromosomes. Consistent with
    # cytozip.bam.bam_to_cz `chroms`: accepts a list/tuple/set of names, a
    # comma-separated string, or a path to a chrom-size / .fai file (first col).
    if chroms is None:
        use_chroms = None
    elif isinstance(chroms, (list, tuple, set)):
        use_chroms = {str(c) for c in chroms}
    else:
        chroms_str = str(chroms)
        chroms_path = os.path.expanduser(chroms_str)
        if os.path.exists(chroms_path):
            use_chroms = set(
                pd.read_csv(chroms_path, sep="\t", header=None,
                            usecols=[0])[0].astype(str)
            )
        elif "," in chroms_str:
            use_chroms = {c for c in chroms_str.split(",") if c}
        else:
            use_chroms = {chroms_str}

    if convert_bam_strandness:
        temp_bam_path = f"{output_path}.temp.bam"
        _convert_bam_strandness(
            in_bam_path=bam_path, out_bam_path=temp_bam_path)
        bam_path = temp_bam_path

    if not pathlib.Path(bam_path + ".bai").exists():
        subprocess.check_call(shlex.split("samtools index " + bam_path))

    # check chromosome between BAM and FASTA
    # samtools have a bug when chromosome not match...
    bam_chroms_index = _get_bam_chrom_index(bam_path)
    if use_chroms is not None:
        # only consider chromosomes in the chroms whitelist
        bam_chroms_index = pd.Index([i for i in bam_chroms_index if i in use_chroms])
        unknown_chroms = [i for i in bam_chroms_index if i not in fai_df.index]
        if len(unknown_chroms) != 0:
            unknown_chroms = " ".join(unknown_chroms)
            raise IndexError(
                f"BAM file contain unknown chromosomes: {unknown_chroms}\n"
                "Make sure you use the same genome FASTA file for mapping and bam-to-allc."
            )
    else:
        # no chroms given: only use chromosomes shared by BAM and FASTA, so
        # contigs missing from the FASTA (e.g. decoy contigs) are ignored instead
        # of raising an error or hanging the parser.
        use_chroms = {i for i in bam_chroms_index if i in fai_df.index}

    # if parallel, chunk genome
    if cpu > 1:
        regions = genome_region_chunks(reference_fasta + ".fai", bin_length=100000000, combine_small=False)
    else:
        regions = None

    # Output path
    input_path = pathlib.Path(bam_path)
    file_dir = input_path.parent
    if output_path is None:
        allc_name = "allc_" + input_path.name.split(".")[0] + ".tsv.gz"
        output_path = str(file_dir / allc_name)
    else:
        if not output_path.endswith(".gz"):
            output_path += ".gz"

    if cpu > 1:
        raise NotImplementedError

        temp_out_paths = []
        for batch_id in range(len(regions)):
            temp_out_paths.append(output_path + f".batch_{batch_id}.tmp.tsv.gz")

        with ProcessPoolExecutor(max_workers=cpu) as executor:
            future_dict = {}
            for batch_id, (region, out_temp_path) in enumerate(zip(regions, temp_out_paths)):
                _kwargs = {
                    "bam_path": bam_path,
                    "reference_fasta": reference_fasta,
                    "fai_df": fai_df,
                    "output_path": out_temp_path,
                    "region": region,
                    "num_upstr_bases": num_upstr_bases,
                    "num_downstr_bases": num_downstr_bases,
                    "buffer_line_number": buffer_line_number,
                    "min_mapq": min_mapq,
                    "min_base_quality": min_base_quality,
                    "compress_level": compress_level,
                    "tabix": False,
                    "save_count_df": False,
                    "use_chroms": use_chroms,
                }
                future_dict[executor.submit(_bam_to_allc_worker, **_kwargs)] = batch_id

            count_dfs = []
            for future in as_completed(future_dict):
                batch_id = future_dict[future]
                try:
                    count_dfs.append(future.result())
                except Exception as exc:
                    log.info(f"{batch_id!r} generated an exception: {exc}")

            # aggregate ALLC
            with open_allc(
                output_path,
                mode="w",
                compresslevel=compress_level,
                threads=1,
                region=None,
            ) as out_f:
                # TODO: Parallel ALLC is overlapped,
                #  the split by region strategy only split reads, but reads can overlap
                # need to adjust and merge end rows in aggregate ALLC
                for out_temp_path in temp_out_paths:
                    with open_allc(out_temp_path) as f:
                        for line in f:
                            out_f.write(line)
                    subprocess.check_call(["rm", "-f", out_temp_path])

            # tabix
            if tabix:
                subprocess.run(shlex.split(f"tabix -b 2 -e 2 -s 1 {output_path}"), check=True)

            # aggregate count_df
            count_df = _aggregate_count_df(count_dfs)
            if save_count_df:
                count_df.to_csv(output_path + ".count.csv")

            # clean up temp bam
            if convert_bam_strandness:
                # this bam path is the temp file path
                subprocess.check_call(["rm", "-f", bam_path])
                subprocess.check_call(["rm", "-f", f"{bam_path}.bai"])
            return count_df
    else:
        result = _bam_to_allc_worker(
            bam_path,
            reference_fasta,
            fai_df,
            output_path,
            region=None,
            num_upstr_bases=num_upstr_bases,
            num_downstr_bases=num_downstr_bases,
            buffer_line_number=buffer_line_number,
            min_mapq=min_mapq,
            min_base_quality=min_base_quality,
            compress_level=compress_level,
            tabix=tabix,
            save_count_df=save_count_df,
            use_chroms=use_chroms,
        )

        # clean up temp bam
        if convert_bam_strandness and not keep_temp:
            # this bam path is the temp file path
            subprocess.check_call(["rm", "-f", bam_path])
            subprocess.check_call(["rm", "-f", f"{bam_path}.bai"])

        return result

def gc_content_calculator(record, outfile, window_size=100, step_size=10):
    chrom = record.id
    seq = str(record.seq).upper()
    seq_len = len(seq)
    results=[]
    # Slide windows
    for start in range(0, seq_len - window_size + 1, step_size):
        end = start + window_size
        window_seq = seq[start:end]
        total_length=window_size-window_seq.count('N')
        if total_length == 0: # skip all N region
            continue
        gc_count = window_seq.count('G') + window_seq.count('C')
        gc_percent = (gc_count / total_length) * 100
        results.append([chrom, start+1, end, gc_percent]) # convert start from 0-based to 1-based
    df=pd.DataFrame(results, columns=['chrom', 'start', 'end', 'gc_percent'])
    df.to_csv(outfile, index=False,sep='\t')
    return chrom

def calculate_gc_content(
        reference_fasta, window_size=100, step_size=10, 
        cpu=1,output_file='gc_content.tsv',tabix=True
    ):
    """
    Calculate GC content for a FASTA file using a sliding window.
    
    Args:
        fasta_file (str): Path to reference FASTA file (e.g., 'hg38.fasta').
        window_size (int): Size of the sliding window (default: 100 bp).
        step_size (int): Step size for sliding window (default: 10 bp).
        cpu (int): Number of CPU to run in parallel.
        output_file (str): Path to save GC content results as CSV (default: 'gc_content.csv').
    
    Returns:
        pandas.DataFrame: DataFrame with columns: chrom, start (1-based), end, gc_percent
    """
    from Bio import SeqIO
    output_file=os.path.expanduser(output_file)
    tmp_folder=f"{output_file}.tmp"
    if not os.path.exists(tmp_folder):
        os.makedirs(tmp_folder,exist_ok=True)
    # Parse FASTA file
    records = SeqIO.parse(reference_fasta, "fasta")
    chroms=[]
    with ProcessPoolExecutor(cpu) as executor:
        futures = []
        for record in records:
            chrom = record.id
            outfile=f"{tmp_folder}/{chrom}.gc.tsv"
            chroms.append(chrom)
            if os.path.exists(outfile):
                # print("existed:",outfile)
                continue
            future = executor.submit(gc_content_calculator, record=record, 
                                     outfile=outfile, window_size=window_size, step_size=step_size)
            futures.append(future)
        for future in as_completed(futures):
            chrom = future.result()
            print(chrom)
        
    # Merge results
    print("Merging chromosomes..")
    for chrom in sorted(chroms): # sort the chromosomes to run bgzip
        outfile=f"{tmp_folder}/{chrom}.gc.tsv"
        df=pd.read_csv(outfile, sep='\t')
        if not os.path.exists(output_file):
            df.to_csv(output_file,sep='\t',header=False,index=False)
        else:
            df.to_csv(output_file,sep='\t',header=False,index=False,mode='a')
    os.system(f"rm -rf {tmp_folder}")
    if tabix:
        print("Running bgzip and tabix..")
        subprocess.run(shlex.split(f"bgzip {output_file}"), check=True)
        subprocess.run(shlex.split(f"tabix -b 2 -e 2 -s 1 {output_file}.gz"), check=True)
        return f"{output_file}.gz" # 0-based
    else:
        return output_file

def gc_allc_intersect(allc_path,gc_content,chrom,outfile,window_size):
    f_allc=pysam.TabixFile(allc_path)
    f_gc=pysam.TabixFile(os.path.expanduser(gc_content))
    # Load ALLC pos and cov for chrom
    pos_allc = []
    cov_allc = []
    for r in f_allc.fetch(chrom):
        f = r.split('\t')
        pos_allc.append(int(f[1]))
        cov_allc.append(int(f[5]))
    pos_allc = np.array(pos_allc)
    cov_allc = np.array(cov_allc, dtype=np.float64)
    f_allc.close()
    # Compute prefix sums
    prefix_cov = np.concatenate([np.zeros(1), np.cumsum(cov_allc)]) # add a zero to the beginning
    # Load GC starts, ends, gc_percents for chrom
    starts = []
    gc_percents = []
    for r in f_gc.fetch(chrom):
        f = r.split('\t')
        starts.append(int(f[1]))
        gc_percents.append(float(f[3]))
    starts = np.array(starts)
    ends = starts + window_size-1
    f_gc.close()
    
    # Compute left and right indices
    #finds the indices where values (starts) should be inserted into a sorted array (pos_allc) to maintain its sorted order, identify which ALLC file positions fall within each GC content window
    # example: # Sorted array of ALLC positions (1-based, as in your ALLC file)
    # a = np.array([100, 120, 130, 150])
    # v = np.array([100, 125, 149,151,200])
    # np.searchsorted(a, v, side='left') #results: array([0, 2, 3,4,4])
    # np.searchsorted(a, v, side='right') #results: array([1, 2, 3, 4,4 ])

    lefts = np.searchsorted(pos_allc, starts, side='left') # right: a[i-1] <= v < a[i]
    rights = np.searchsorted(pos_allc, ends, side='right') # left: a[i-1] < v <= a[i]
    # Compute sums and counts
    sums_cov = prefix_cov[rights] - prefix_cov[lefts]
    counts = rights - lefts
    # Compute means
    means = np.zeros(len(starts))
    mask = counts > 0
    means[mask] = sums_cov[mask] / counts[mask]
    df=pd.DataFrame({'chrom':chrom,'start':starts,'end':ends,'gc_percent':gc_percents,'mean_cov':means,'counts':counts})
    df.to_csv(outfile,sep='\t',index=False)
    return outfile

def correct_allc(
        allc_dir=None,allc_table=None, gc_content=None, cpu=1, 
        outdir=None, lowess_downsample=None,
        compress_level=5,ext=".allc.tsv.gz",window_size=100,num_bins=50, 
        frac=0.2,it=3, delta=0.01,keep_temp=False,correct=True
        ):
    """
    Correct the coverage bias caused by the GC content (such as the global methylation
    fraction difference between NovaSeq 6000 and NovaSeq X du to the denaturation time)
    
    Args:
        allc_path (str): Path to allc file.
        window_size (int): Sliding window size for GC calculation (default: 100 bp).
        num_bins (int): Number of GC bins (default: 25).
        smoothing_fraction (float): Fraction for LOWESS smoothing (default: 0.1).
    
    Returns:
        None (writes ALLC file and optionally a count DataFrame).
    """
    assert not gc_content is None, "Please provide GC content file"
    assert not outdir is None
    gc_content=os.path.expanduser(gc_content)
    if allc_table is None:
        assert not allc_dir is None
        allc_dir=os.path.expanduser(allc_dir)
        R=[]
        for allc_path in glob.glob(os.path.join(allc_dir,f"*{ext}")):
            sname=os.path.basename(allc_path).replace(ext,'')
            R.append([sname,allc_path])
        allc_table=pd.DataFrame(R,columns=['sname','path'])
    else:
        allc_table=pd.read_csv(os.path.expanduser(allc_table),sep='\t',
            header=None,names=['sname','path'])

    os.makedirs(outdir,exist_ok=True)
    if lowess_downsample is None or lowess_downsample >= allc_table.shape[0]:
        train_allc_paths=allc_table.path.tolist()
    else:
        assert isinstance(lowess_downsample,int)
        train_allc_paths=allc_table.sample(lowess_downsample).path.tolist()
    if not os.path.exists(f"{outdir}/lowess.pkl"):
        calculate_mean_cov(
            allc_paths=train_allc_paths,gc_content=gc_content,outdir=outdir,
            cpu=cpu,window_size=window_size,num_bins=num_bins, 
            frac=frac,it=it,delta=delta,keep_temp=keep_temp)
    if not correct:
        return None
    f=open(f"{outdir}/lowess.pkl",'rb')
    gc_bins,bin_means,correction_factors=pickle.load(f)
    f.close()
    df=pd.read_csv(f"{outdir}/merged_mean_cov.tsv",sep='\t')
    
    # correct each allc file based on fitted model
    for sname,allc_path in allc_table.loc[:,['sname','path']].values:
        print(sname)
        outfile=f"{outdir}/{sname}.allc.tsv"
        f_allc=pysam.TabixFile(allc_path)
        for chrom in f_allc.contigs:
            # read allc into dataframe
            records=f_allc.fetch(chrom)
            R=[]
            for record in records:
                R.append(record.split('\t'))
            df_meth=pd.DataFrame(R,columns=['chrom', 'start', 'strand', 'context','mc','cov','flag'])
            df_meth.start=df_meth.start.astype(int)
            df_meth.mc=df_meth.mc.astype(int)
            df_meth['cov']=df_meth['cov'].astype(int)
            # df_gc
            df_gc=df.loc[df.chrom==chrom]
            rights = np.searchsorted(df_gc.start.values, df_meth.start.values, side='right') # left: a[i-1] < v <= a[i]; right: a[i-1] <= v < a[i]
            lefts = np.searchsorted(df_gc.end.values, df_meth.start.values, side='left')
            gc_percents=df_gc.gc_percent.values
            # map gc_percents to gc_bins
            df_meth['avg_gc_percent'] = [np.mean(gc_percents[left:right]) if left < right else np.nan for left, right in zip(lefts, rights)]
            df_meth['gc_bin']=np.searchsorted(gc_bins, df_meth['avg_gc_percent'].values, side='right') - 1
            df_meth['correction_factor'] = df_meth['gc_bin'].apply(lambda b: correction_factors[b] if not np.isnan(b) else 1.0)
            df_meth['corrected_mc'] = np.round(df_meth['mc'] * df_meth['correction_factor']).astype(int)
            df_meth['corrected_cov'] = np.round(df_meth['cov'] * df_meth['correction_factor']).astype(int)
            df_meth=df_meth.loc[:,['chrom','start','strand','context','corrected_mc','corrected_cov','flag']]
            if not os.path.exists(outfile):
                df_meth.to_csv(outfile,sep='\t',index=False,header=False)
            else:
                df_meth.to_csv(outfile,sep='\t',index=False,header=False,mode='a')
        f_allc.close()
        # Compress and index
        subprocess.call(f"bgzip -f -l {compress_level} {outfile}", shell=True)
        subprocess.call(f"tabix -b 2 -e 2 -s 1  {outfile}.gz", shell=True)
    
def test():
    reference_fasta="/anvil/projects/x-mcb130189/kaushik2/mapping/mapping_ref/genome/fasta/with_chrl/mm10_with_chrl.fa"
    chrom_size_path="/anvil/projects/x-mcb130189/kaushik2/mapping/mapping_ref/genome/fasta/with_chrl/mm10_with_chrl.chrom.sizes"
    gc_content="mm10.500bp.GC.content.bed"
    for bam_path in glob.glob("NovaSeq*.corrected/*.bam"):
        # bam_path="CEMBAL_4AR_M1_2-2-F6-P3.final.bam"
        allc_path=bam_path.replace('.final.bam','.allc.tsv.gz')
        folder=os.path.dirname(bam_path)
        if not os.path.exists(allc_path):
            bam_to_allc(
                bam_path,
                reference_fasta,
                output_path=allc_path,
                cpu=1,
                num_upstr_bases=0,
                num_downstr_bases=2,
                min_mapq=10,
                min_base_quality=20,
                compress_level=5,
                save_count_df=True,
                convert_bam_strandness=True,keep_temp=True,
                )
    
    # samtools depth -o depth.tsv -Q 10 -q 20 -@ 8 CEMBAL_12AR_M1_P2-5-M17-P21.final.bam
    # average coverage: awk '{sum += $3; count++} END {print(sum / count)}' depth.tsv

    # computeGCBias -b CEMBAL_12AR_M1_P2-5-M17-P21.final.bam --effectiveGenomeSize 2700000000 -g /home/x-wding2/scratch/test/hg38.2bit --fragmentLength 150 --biasPlot gc_bias_plot.pdf --plotFileFormat pdf -o gc_bias.txt

    # bedtools makewindows -g ${chrom_size_path} -w 500 > mm10.500bp.bed # 0-based
    # #bedtools nuc -fi ${reference_fasta} -bed mm10.500bp.bed | sed '1d' | cut -f 1-3,5 > mm10.500bp.GC.content.bed # 0-based
    # bedtools nuc -fi ${reference_fasta} -bed mm10.500bp.bed | sed '1d' | awk '{print($1"-"int($2/500)"\t"$1"\t"$2"\t"$3"\t"$5)}' > mm10.500bp.GC.content.bed
    # samtools depth -q 20 -Q 10 -J -@ 8 NovaSeq6000/CEMBAL_12AR_M1_P2-5-M17-P21.final.bam | awk '{print($1"-"int($2/500)"\t"$3)}' > NovaSeq6000/depth.txt # 1-based
