name: Check Build

on:
    push:
        branches: ["*"]
    pull_request:
        branches: ["*"]

jobs:
    package:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: "3.8"
            - name: Install build dependencies
              run: python -m pip install --upgrade pip wheel twine build
            - name: Build package
              run: python -m build
            - name: Check package
              run: twine check --strict dist/*.whl
